export const backendPaths = {
  listings: {
    create: '/listings',
    search: '/listings/search',
    getBySlug: (slug: string) => `/listings/slug/${slug}`,
    getById: (id: string) => `/listings/${id}`,
    photos: (id: string) => `/listings/${id}/photos`,
    nearByPoints: (id: string) => `/listings/${id}/near-by-points`,
    saved: '/listings/saved',
    favoriteFilters: '/listings/favorite-filters',
    favoriteFilterById: (id: string) => `/listings/favorite-filters/${id}`,
    checkSaved: '/listings/saved/check',
    save: (id: string) => `/listings/${id}/save`,
    view: (id: string) => `/listings/${id}/view`,
    myReports: '/listings/my-reports',
    reports: '/listings/reports',
    report: (id: string) => `/listings/${id}/report`,
    reportById: (reportId: string) => `/listings/reports/${reportId}`,
    myViewHistory: '/listings/my-view-history',
    myViewHistoryEntry: (listingId: string) => `/listings/my-view-history/${listingId}`,
    myListings: '/listings/my-listings',
    mine: (id: string) => `/listings/${id}/mine`,
    publish: (id: string) => `/listings/${id}/publish`,
    draft: (id: string) => `/listings/${id}/draft`,
    sold: (id: string) => `/listings/${id}/sold`,
    rented: (id: string) => `/listings/${id}/rented`,
    softDelete: (id: string) => `/listings/${id}/soft-delete`,
    restore: (id: string) => `/listings/${id}/restore`,
    officeAnalytics: (officeId: string) => `/listings/offices/${officeId}/analytics`,
    officeUserAnalytics: (officeId: string) => `/listings/offices/${officeId}/user-analytics`,
    historyLatest: (id: string) => `/listings/${id}/history/latest`,
    adminList: '/listings/admin',
    adminDetail: (id: string) => `/listings/admin/${id}`,
    adminListingActionLogs: (id: string) => `/listings/admin/${id}/action-logs`,
    listingOfficeActionLogs: (id: string) => `/listings/${id}/office-action-logs`,
    adminBulk: '/listings/admin/bulk',
    deleteImage: (id: string) => `/listings/${id}/images`,
    deleteImagesBulk: (id: string) => `/listings/${id}/images/bulk`,
    deleteVideo: (id: string) => `/listings/${id}/video`,
    setMainImage: (id: string) => `/listings/${id}/images/main`,
    setImagesOrder: (id: string) => `/listings/${id}/images/order`,
  },
  cities: {
    public: '/cities/public',
    byPcode: (pcode: string) => `/cities/public/pcode/${pcode}`,
    admin: '/cities',
    adminById: (id: string) => `/cities/${id}`,
  },
  propertyTypes: {
    public: '/property-types/public',
    publicHomeListings: '/property-types/public/home-listings',
    bySlug: (slug: string) => `/property-types/public/slug/${slug}`,
    admin: '/property-types',
    adminById: (id: string) => `/property-types/${id}`,
    adminActivate: (id: string) => `/property-types/${id}/activate`,
    adminDeactivate: (id: string) => `/property-types/${id}/deactivate`,
  },
  propertySubtypes: {
    byPropertyType: (propertyTypeId: string) => `/property-subtypes/public/${propertyTypeId}`,
    bySlug: (slug: string) => `/property-subtypes/public/slug/${slug}`,
    admin: '/property-subtypes',
    adminById: (id: string) => `/property-subtypes/${id}`,
  },
  transactionTypes: {
    public: '/transaction-types/public',
    bySlug: (slug: string) => `/transaction-types/public/slug/${slug}`,
    admin: '/transaction-types',
    adminById: (id: string) => `/transaction-types/${id}`,
  },
  neighborhoods: {
    public: '/neighborhoods/public',
    byPcode: (neighbPcode: string) => `/neighborhoods/public/pcode/${neighbPcode}`,
    admin: '/neighborhoods',
    adminById: (id: string) => `/neighborhoods/${id}`,
  },
  features: {
    public: '/features',
    admin: '/features',
    adminById: (id: string) => `/features/${id}`,
    adminSub: '/features/sub',
    adminSubById: (id: string) => `/features/sub/${id}`,
    adminSubBulkDelete: '/features/sub/bulk',
  },
  offices: {
    my: '/offices/my',
    myDeleted: '/offices/my/deleted',
    create: '/offices',
    list: '/offices',
    public: '/offices/public',
    publicByName: (name: string) => `/offices/public/by-name/${encodeURIComponent(name)}`,
    publicListingsByName: (name: string) => `/offices/public/by-name/${encodeURIComponent(name)}/listings`,
    emailVerificationSend: '/offices/email-verification/send',
    emailVerificationVerify: '/offices/email-verification/verify',
    byId: (id: string) => `/offices/${id}`,
    update: (id: string) => `/offices/${id}`,
    resubmit: (id: string) => `/offices/${id}/resubmit`,
    addUser: (id: string) => `/offices/${id}/users`,
    removeUsers: (id: string) => `/offices/${id}/users`,
    verify: (id: string) => `/offices/${id}/verify`,
    reject: (id: string) => `/offices/${id}/reject`,
    suspend: (id: string) => `/offices/${id}/suspend`,
    unsuspend: (id: string) => `/offices/${id}/unsuspend`,
    softDelete: (id: string) => `/offices/${id}/soft-delete`,
    restore: (id: string) => `/offices/${id}/restore`,
    delete: (id: string) => `/offices/${id}`,
    bulk: '/offices/bulk',
    userActionLogs: (officeId: string, userId: string) => `/offices/${officeId}/users/${userId}/action-logs`,
  },
  individualListers: {
    my: '/individual-listers/my',
    create: '/individual-listers',
    list: '/individual-listers',
    verify: (id: string) => `/individual-listers/${id}/verify`,
    reject: (id: string) => `/individual-listers/${id}/reject`,
    suspend: (id: string) => `/individual-listers/${id}/suspend`,
    unsuspend: (id: string) => `/individual-listers/${id}/unsuspend`,
    softDelete: (id: string) => `/individual-listers/${id}/soft-delete`,
    restore: (id: string) => `/individual-listers/${id}/restore`,
    delete: (id: string) => `/individual-listers/${id}`,
    bulk: '/individual-listers/bulk',
  },
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
    meDeleteProfileImage: '/auth/me/delete-profile-image',
    logout: '/auth/logout',
    refreshToken: '/auth/refresh-token',
    verifyEmail: '/auth/verify-email',
    forgotPassword: '/auth/forgot-password',
    sendCode: '/auth/send-code',
    changePassword: '/auth/change-password',
    users: '/admin/users',
    userById: (userId: string) => `/admin/users/${userId}`,
    activateUser: (userId: string) => `/admin/users/${userId}/activate`,
    deactivateUser: (userId: string) => `/admin/users/${userId}/deactivate`,
    changeUserRole: (userId: string) => `/admin/users/${userId}/change-role`,
    changeUserPassword: (userId: string) => `/admin/users/${userId}/change-password`,
    softDeleteUser: (userId: string) => `/admin/users/${userId}/soft-delete`,
    restoreUser: (userId: string) => `/admin/users/${userId}/restore`,
    usersBulk: '/admin/users/bulk',
    actionLogsLatest: '/admin/action-logs/latest',
    actionLogsByEntity: (entityId: string) => `/admin/action-logs/entity/${entityId}`,
    officeActionLogs: '/admin/office-action-logs',
    officeActionLogsBulk: '/admin/office-action-logs/bulk',
    navBadges: '/admin/nav-badges',
    dashboard: '/admin/dashboard',
    systemStatus: '/admin/system-status',
    permissionsMe: '/admin/permissions/me',
    permissions: '/admin/permissions',
    permissionAssignments: '/admin/permissions/assignments',
    permissionAssign: '/admin/permissions/assign',
    permissionAssignBulk: '/admin/permissions/assign/bulk',
    permissionAssignUser: '/admin/permissions/assign/user',
    permissionById: (id: string) => `/admin/permissions/${id}`,
    subAdminsSearch: '/admin/permissions/sub-admins/search',
  },
  messaging: {
    conversations: '/messaging/conversations',
    conversation: (id: string) => `/messaging/conversations/${id}`,
    messages: (id: string) => `/messaging/conversations/${id}/messages`,
    listingImage: (id: string) => `/messaging/conversations/${id}/messages/listing-image`,
    message: (id: string, messageId: string) => `/messaging/conversations/${id}/messages/${messageId}`,
    block: (id: string) => `/messaging/conversations/${id}/block`,
    report: (id: string) => `/messaging/conversations/${id}/report`,
    read: (id: string) => `/messaging/conversations/${id}/read`,
    unreadCount: '/messaging/conversations/unread-count',
    myReports: '/messaging/my-reports',
    socketTicket: '/messaging/socket-ticket',
    deviceTokens: '/messaging/device-tokens',
    admin: {
      conversations: '/messaging/admin/conversations',
      conversation: (id: string) => `/messaging/admin/conversations/${id}`,
      messages: (id: string) => `/messaging/admin/conversations/${id}/messages`,
      blocks: (id: string) => `/messaging/admin/conversations/${id}/blocks`,
      reports: '/messaging/admin/reports',
      reportById: (reportId: string) => `/messaging/admin/reports/${reportId}`,
    },
  },
  supportTickets: {
    canCreate: '/support-tickets/can-create',
    tickets: '/support-tickets/tickets',
    ticket: (id: string) => `/support-tickets/tickets/${id}`,
    messages: (id: string) => `/support-tickets/tickets/${id}/messages`,
    messagesMedia: (id: string) => `/support-tickets/tickets/${id}/messages/media`,
    admin: {
      tickets: '/support-tickets/admin/tickets',
      ticket: (id: string) => `/support-tickets/admin/tickets/${id}`,
      messages: (id: string) => `/support-tickets/admin/tickets/${id}/messages`,
      messagesMedia: (id: string) => `/support-tickets/admin/tickets/${id}/messages/media`,
      status: (id: string) => `/support-tickets/admin/tickets/${id}/status`,
    },
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
  },
  announcements: {
    byId: (id: string) => `/announcements/${id}`,
    admin: {
      list: '/announcements/admin',
      estimateAudience: '/announcements/admin/estimate-audience',
      draft: '/announcements/admin/draft',
      send: '/announcements/admin/send',
      byId: (id: string) => `/announcements/admin/${id}`,
    },
  },
  websiteSettings: {
    public: '/website-settings',
    admin: '/website-settings/admin',
  },
} as const;

export const bffPaths = {
  offices: {
    create: '/api/offices',
    myDeleted: '/api/offices/my/deleted',
    public: '/api/offices/public',
    publicByName: (name: string) => `/api/offices/public/${encodeURIComponent(name)}`,
    publicListingsByName: (name: string) => `/api/offices/public/${encodeURIComponent(name)}/listings`,
    emailVerificationSend: '/api/offices/email-verification/send',
    emailVerificationVerify: '/api/offices/email-verification/verify',
    update: (id: string) => `/api/offices/${id}`,
    resubmit: (id: string) => `/api/offices/${id}/resubmit`,
    softDelete: (id: string) => `/api/offices/${id}/soft-delete`,
    restore: (id: string) => `/api/offices/${id}/restore`,
    delete: (id: string) => `/api/offices/${id}`,
    users: (id: string) => `/api/offices/${id}/users`,
  },
  individualListers: {
    create: '/api/individual-listers',
  },
  messaging: {
    conversations: '/api/messaging/conversations',
    conversation: (id: string) => `/api/messaging/conversations/${id}`,
    messages: (id: string) => `/api/messaging/conversations/${id}/messages`,
    listingImage: (id: string) => `/api/messaging/conversations/${id}/listing-image`,
    message: (id: string, messageId: string) => `/api/messaging/conversations/${id}/messages/${messageId}`,
    block: (id: string) => `/api/messaging/conversations/${id}/block`,
    report: (id: string) => `/api/messaging/conversations/${id}/report`,
    read: (id: string) => `/api/messaging/conversations/${id}/read`,
    unreadCount: '/api/messaging/conversations/unread-count',
    myReports: '/api/messaging/my-reports',
    socketTicket: '/api/messaging/socket-ticket',
    deviceTokens: '/api/messaging/device-tokens',
    admin: {
      conversations: '/api/messaging/admin/conversations',
      conversation: (id: string) => `/api/messaging/admin/conversations/${id}`,
      messages: (id: string) => `/api/messaging/admin/messages/${id}`,
      blocks: (id: string) => `/api/messaging/admin/blocks/${id}`,
      reports: '/api/messaging/admin/reports',
      reportById: (reportId: string) => `/api/messaging/admin/reports/${reportId}`,
    },
  },
  supportTickets: {
    canCreate: '/api/support-tickets/can-create',
    tickets: '/api/support-tickets/tickets',
    ticket: (id: string) => `/api/support-tickets/tickets/${id}`,
    messages: (id: string) => `/api/support-tickets/tickets/${id}/messages`,
    messagesMedia: (id: string) => `/api/support-tickets/tickets/${id}/media`,
    admin: {
      tickets: '/api/support-tickets/admin/tickets',
      ticket: (id: string) => `/api/support-tickets/admin/tickets/${id}`,
      messages: (id: string) => `/api/support-tickets/admin/messages/${id}`,
      messagesMedia: (id: string) => `/api/support-tickets/admin/media/${id}`,
      status: (id: string) => `/api/support-tickets/admin/tickets/${id}/status`,
    },
  },
  notifications: {
    list: '/api/notifications',
    unreadCount: '/api/notifications/unread-count',
    markRead: (id: string) => `/api/notifications/${id}/read`,
    markAllRead: '/api/notifications/read-all',
  },
  announcements: {
    byId: (id: string) => `/api/announcements/${id}`,
    admin: {
      list: '/api/announcements/admin',
      estimateAudience: '/api/announcements/admin/estimate-audience',
      draft: '/api/announcements/admin/draft',
      send: '/api/announcements/admin/send',
      byId: (id: string) => `/api/announcements/admin/${id}`,
    },
  },
  listings: {
    search: '/api/listings/search',
    nearByPoints: (id: string) => `/api/listings/${id}/near-by-points`,
    save: (id: string) => `/api/listings/${id}/save`,
    view: (id: string) => `/api/listings/${id}/view`,
    saved: '/api/listings/saved',
    favoriteFilters: '/api/listings/favorite-filters',
    favoriteFilterById: (id: string) => `/api/listings/favorite-filters/${id}`,
    checkSaved: '/api/listings/saved/check',
    myReports: '/api/listings/my-reports',
    reports: '/api/listings/reports',
    report: (id: string) => `/api/listings/${id}/report`,
    reportById: (reportId: string) => `/api/listings/reports/${reportId}`,
    myViewHistory: '/api/listings/my-view-history',
    myViewHistoryEntry: (listingId: string) => `/api/listings/my-view-history/${listingId}`,
    myListings: '/api/listings/my-listings',
    create: '/api/listings',
    byId: (id: string) => `/api/listings/${id}`,
    photos: (id: string) => `/api/listings/${id}/photos`,
    publish: (id: string) => `/api/listings/${id}/publish`,
    draft: (id: string) => `/api/listings/${id}/draft`,
    sold: (id: string) => `/api/listings/${id}/sold`,
    rented: (id: string) => `/api/listings/${id}/rented`,
    softDelete: (id: string) => `/api/listings/${id}/soft-delete`,
    restore: (id: string) => `/api/listings/${id}/restore`,
    delete: (id: string) => `/api/listings/${id}`,
    deleteImage: (id: string) => `/api/listings/${id}/images`,
    deleteVideo: (id: string) => `/api/listings/${id}/video`,
    setMainImage: (id: string) => `/api/listings/${id}/images/main`,
    setImagesOrder: (id: string) => `/api/listings/${id}/images/order`,
    officeActionLogs: (id: string) => `/api/listings/${id}/office-action-logs`,
    officeAnalytics: (officeId: string) => `/api/listings/offices/${officeId}/analytics`,
    officeUserAnalytics: (officeId: string) => `/api/listings/offices/${officeId}/user-analytics`,
    historyLatest: (id: string) => `/api/listings/${id}/history/latest`,
  },
  cities: {
    public: '/api/cities/public',
  },
  propertyTypes: {
    public: '/api/property-types/public',
    publicHomeListings: '/api/property-types/public/home-listings',
  },
  transactionTypes: {
    public: '/api/transaction-types/public',
  },
  neighborhoods: {
    public: '/api/neighborhoods/public',
  },
  propertySubtypes: {
    byPropertyType: (propertyTypeId: string) => `/api/property-subtypes/public/${propertyTypeId}`,
  },
  auth: {
    login: '/api/auth/login',
    logout: '/api/auth/logout',
    me: '/api/auth/me',
    meDeleteProfileImage: '/api/auth/me/delete-profile-image',
    register: '/api/auth/register',
    verifyEmail: '/api/auth/verify-email',
    forgotPassword: '/api/auth/forgot-password',
    refreshToken: '/api/auth/refresh-token',
    sendCode: '/api/auth/send-code',
    changePassword: '/api/auth/change-password',
  },
  admin: {
    users: '/api/admin/users',
    userById: (userId: string) => `/api/admin/users/${userId}`,
    activateUser: (userId: string) => `/api/admin/users/${userId}/activate`,
    deactivateUser: (userId: string) => `/api/admin/users/${userId}/deactivate`,
    changeUserRole: (userId: string) => `/api/admin/users/${userId}/change-role`,
    changeUserPassword: (userId: string) => `/api/admin/users/${userId}/change-password`,
    softDeleteUser: (userId: string) => `/api/admin/users/${userId}/soft-delete`,
    restoreUser: (userId: string) => `/api/admin/users/${userId}/restore`,
    usersBulk: '/api/admin/users/bulk',
    actionLogsLatest: '/api/admin/action-logs/latest',
    actionLogsByEntity: (entityId: string) => `/api/admin/action-logs/entity/${entityId}`,
    officeActionLogs: '/api/admin/office-action-logs',
    officeActionLogsBulk: '/api/admin/office-action-logs/bulk',
    listingActionLogs: (id: string) => `/api/admin/listings/${id}/action-logs`,
    propertyTypes: '/api/admin/property-types',
    propertyTypeById: (id: string) => `/api/admin/property-types/${id}`,
    activatePropertyType: (id: string) => `/api/admin/property-types/${id}/activate`,
    deactivatePropertyType: (id: string) => `/api/admin/property-types/${id}/deactivate`,
    propertySubtypes: '/api/admin/property-subtypes',
    propertySubtypeById: (id: string) => `/api/admin/property-subtypes/${id}`,
    transactionTypes: '/api/admin/transaction-types',
    transactionTypeById: (id: string) => `/api/admin/transaction-types/${id}`,
    cities: '/api/admin/cities',
    cityById: (id: string) => `/api/admin/cities/${id}`,
    neighborhoods: '/api/admin/neighborhoods',
    neighborhoodById: (id: string) => `/api/admin/neighborhoods/${id}`,
    features: '/api/admin/features',
    featureById: (id: string) => `/api/admin/features/${id}`,
    subFeatures: '/api/admin/features/sub',
    subFeatureById: (id: string) => `/api/admin/features/sub/${id}`,
    subFeaturesBulkDelete: '/api/admin/features/sub/bulk',
    offices: '/api/admin/offices',
    officeById: (id: string) => `/api/admin/offices/${id}`,
    officeVerify: (id: string) => `/api/admin/offices/${id}/verify`,
    officeReject: (id: string) => `/api/admin/offices/${id}/reject`,
    officeSuspend: (id: string) => `/api/admin/offices/${id}/suspend`,
    officeUnsuspend: (id: string) => `/api/admin/offices/${id}/unsuspend`,
    officeSoftDelete: (id: string) => `/api/admin/offices/${id}/soft-delete`,
    officeRestore: (id: string) => `/api/admin/offices/${id}/restore`,
    officeUsers: (id: string) => `/api/admin/offices/${id}/users`,
    officesBulk: '/api/admin/offices/bulk',
    individualListers: '/api/admin/individual-listers',
    individualListerVerify: (id: string) => `/api/admin/individual-listers/${id}/verify`,
    individualListerReject: (id: string) => `/api/admin/individual-listers/${id}/reject`,
    individualListerSuspend: (id: string) => `/api/admin/individual-listers/${id}/suspend`,
    individualListerUnsuspend: (id: string) => `/api/admin/individual-listers/${id}/unsuspend`,
    individualListerSoftDelete: (id: string) => `/api/admin/individual-listers/${id}/soft-delete`,
    individualListerRestore: (id: string) => `/api/admin/individual-listers/${id}/restore`,
    individualListerById: (id: string) => `/api/admin/individual-listers/${id}`,
    listings: '/api/admin/listings',
    listingsBulk: '/api/admin/listings/bulk',
    navBadges: '/api/admin/nav-badges',
    systemStatus: '/api/admin/system-status',
    permissionsMe: '/api/admin/permissions/me',
    permissions: '/api/admin/permissions',
    permissionAssignments: '/api/admin/permissions/assignments',
    permissionAssign: '/api/admin/permissions/assign',
    permissionAssignBulk: '/api/admin/permissions/assign/bulk',
    permissionAssignUser: '/api/admin/permissions/assign/user',
    permissionById: (id: string) => `/api/admin/permissions/${id}`,
    subAdminsSearch: '/api/admin/permissions/sub-admins/search',
  },
  websiteSettings: {
    public: '/api/website-settings',
    admin: '/api/website-settings/admin',
  },
} as const;
