export const backendPaths = {
  listings: {
    search: '/listings/search',
    byId: (id: string) => `/listings/${id}`,
    nearByPoints: (id: string) => `/listings/${id}/near-by-points`,
    saved: '/listings/saved',
    save: (id: string) => `/listings/${id}/save`,
    view: (id: string) => `/listings/${id}/view`,
  },
  cities: {
    public: '/cities/public',
    byPcode: (pcode: string) => `/cities/public/pcode/${pcode}`,
    admin: '/cities',
    adminById: (id: string) => `/cities/${id}`,
  },
  propertyTypes: {
    public: '/property-types/public',
    publicHomeListings: '/property-types/public/home-listings',
    bySlug: (slug: string) => `/property-types/public/slug/${slug}`,
    admin: '/property-types',
    adminById: (id: string) => `/property-types/${id}`,
    adminActivate: (id: string) => `/property-types/${id}/activate`,
    adminDeactivate: (id: string) => `/property-types/${id}/deactivate`,
  },
  propertySubtypes: {
    byPropertyType: (propertyTypeId: string) => `/property-subtypes/public/${propertyTypeId}`,
    bySlug: (slug: string) => `/property-subtypes/public/slug/${slug}`,
    admin: '/property-subtypes',
    adminById: (id: string) => `/property-subtypes/${id}`,
  },
  transactionTypes: {
    public: '/transaction-types/public',
    bySlug: (slug: string) => `/transaction-types/public/slug/${slug}`,
    admin: '/transaction-types',
    adminById: (id: string) => `/transaction-types/${id}`,
  },
  neighborhoods: {
    public: '/neighborhoods/public',
    byPcode: (neighbPcode: string) => `/neighborhoods/public/pcode/${neighbPcode}`,
    admin: '/neighborhoods',
    adminById: (id: string) => `/neighborhoods/${id}`,
  },
  features: {
    public: '/features',
    admin: '/features',
    adminById: (id: string) => `/features/${id}`,
    adminSub: '/features/sub',
    adminSubById: (id: string) => `/features/sub/${id}`,
    adminSubBulkDelete: '/features/sub/bulk',
  },
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
    logout: '/auth/logout',
    refreshToken: '/auth/refresh-token',
    verifyEmail: '/auth/verify-email',
    forgotPassword: '/auth/forgot-password',
    sendCode: '/auth/send-code',
    changePassword: '/auth/change-password',
    users: '/admin/users',
    userById: (userId: string) => `/admin/users/${userId}`,
    activateUser: (userId: string) => `/admin/users/${userId}/activate`,
    deactivateUser: (userId: string) => `/admin/users/${userId}/deactivate`,
    changeUserRole: (userId: string) => `/admin/users/${userId}/change-role`,
    changeUserPassword: (userId: string) => `/admin/users/${userId}/change-password`,
    softDeleteUser: (userId: string) => `/admin/users/${userId}/soft-delete`,
    restoreUser: (userId: string) => `/admin/users/${userId}/restore`,
  },
} as const;

export const bffPaths = {
  listings: {
    search: '/api/listings/search',
    nearByPoints: (id: string) => `/api/listings/${id}/near-by-points`,
    save: (id: string) => `/api/listings/${id}/save`,
    view: (id: string) => `/api/listings/${id}/view`,
  },
  cities: {
    public: '/api/cities/public',
  },
  propertyTypes: {
    public: '/api/property-types/public',
    publicHomeListings: '/api/property-types/public/home-listings',
  },
  transactionTypes: {
    public: '/api/transaction-types/public',
  },
  neighborhoods: {
    public: '/api/neighborhoods/public',
  },
  propertySubtypes: {
    byPropertyType: (propertyTypeId: string) => `/api/property-subtypes/public/${propertyTypeId}`,
  },
  auth: {
    login: '/api/auth/login',
    logout: '/api/auth/logout',
    me: '/api/auth/me',
    register: '/api/auth/register',
    verifyEmail: '/api/auth/verify-email',
    forgotPassword: '/api/auth/forgot-password',
    refreshToken: '/api/auth/refresh-token',
    sendCode: '/api/auth/send-code',
    changePassword: '/api/auth/change-password',
  },
  admin: {
    users: '/api/admin/users',
    userById: (userId: string) => `/api/admin/users/${userId}`,
    activateUser: (userId: string) => `/api/admin/users/${userId}/activate`,
    deactivateUser: (userId: string) => `/api/admin/users/${userId}/deactivate`,
    changeUserRole: (userId: string) => `/api/admin/users/${userId}/change-role`,
    changeUserPassword: (userId: string) => `/api/admin/users/${userId}/change-password`,
    softDeleteUser: (userId: string) => `/api/admin/users/${userId}/soft-delete`,
    restoreUser: (userId: string) => `/api/admin/users/${userId}/restore`,
    propertyTypes: '/api/admin/property-types',
    propertyTypeById: (id: string) => `/api/admin/property-types/${id}`,
    activatePropertyType: (id: string) => `/api/admin/property-types/${id}/activate`,
    deactivatePropertyType: (id: string) => `/api/admin/property-types/${id}/deactivate`,
    propertySubtypes: '/api/admin/property-subtypes',
    propertySubtypeById: (id: string) => `/api/admin/property-subtypes/${id}`,
    transactionTypes: '/api/admin/transaction-types',
    transactionTypeById: (id: string) => `/api/admin/transaction-types/${id}`,
    cities: '/api/admin/cities',
    cityById: (id: string) => `/api/admin/cities/${id}`,
    neighborhoods: '/api/admin/neighborhoods',
    neighborhoodById: (id: string) => `/api/admin/neighborhoods/${id}`,
    features: '/api/admin/features',
    featureById: (id: string) => `/api/admin/features/${id}`,
    subFeatures: '/api/admin/features/sub',
    subFeatureById: (id: string) => `/api/admin/features/sub/${id}`,
    subFeaturesBulkDelete: '/api/admin/features/sub/bulk',
  },
} as const;
