export interface WebsiteSettings {
  id: string;
  title: string;
  description: string | null;
  website_email: string | null;
  website_phone: string | null;
  support_email: string | null;
  legal_entity_name: string | null;
  address_text: string | null;
  header_logo_url: string | null;
  header_logo_public_id: string | null;
  footer_logo_url: string | null;
  footer_logo_public_id: string | null;
  favicon_url: string | null;
  favicon_public_id: string | null;
  og_image_url: string | null;
  og_image_public_id: string | null;
  default_listing_og_fallback_url: string | null;
  default_listing_og_fallback_public_id: string | null;
  facebook: string | null;
  instagram: string | null;
  whatsapp: string | null;
  tiktok: string | null;
  site_url: string | null;
  meta_title: string | null;
  meta_description: string | null;
  meta_keywords: string | null;
  robots: string;
  twitter_card: string;
  twitter_handle: string | null;
  default_locale: string;
  theme_color: string;
  google_site_verification: string | null;
  google_analytics_id: string | null;
  facebook_domain_verification: string | null;
  index_listing_search_pages: boolean;
  index_office_profiles: boolean;
  allow_public_indexing: boolean;
  storefront_mode: 'live' | 'coming_soon' | 'maintenance';
  maintenance_title: string;
  maintenance_message: string;
  coming_soon_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface UpdateWebsiteSettingsPayload {
  title?: string;
  description?: string | null;
  website_email?: string | null;
  website_phone?: string | null;
  support_email?: string | null;
  legal_entity_name?: string | null;
  address_text?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  whatsapp?: string | null;
  tiktok?: string | null;
  site_url?: string | null;
  meta_title?: string | null;
  meta_description?: string | null;
  meta_keywords?: string | null;
  robots?: string;
  twitter_card?: string;
  twitter_handle?: string | null;
  default_locale?: string;
  theme_color?: string;
  google_site_verification?: string | null;
  google_analytics_id?: string | null;
  facebook_domain_verification?: string | null;
  index_listing_search_pages?: boolean;
  index_office_profiles?: boolean;
  allow_public_indexing?: boolean;
  storefront_mode?: 'live' | 'coming_soon' | 'maintenance';
  maintenance_title?: string;
  maintenance_message?: string | null;
  coming_soon_message?: string | null;
  remove_header_logo?: boolean;
  remove_footer_logo?: boolean;
  remove_favicon?: boolean;
  remove_og_image?: boolean;
  remove_default_listing_og_fallback?: boolean;
}
